CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL,
  password TEXT NOT NULL,

  role VARCHAR(50) NOT NULL,
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_role
    FOREIGN KEY (role)
    REFERENCES roles(id)
    ON DELETE CASCADE
);