CREATE TABLE IF NOT EXISTS reservations (
  id SERIAL PRIMARY KEY,
  voyage_id INTEGER REFERENCES voyages(id) ON DELETE CASCADE,
  nom VARCHAR(100) NOT NULL,
  places INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);