CREATE TABLE IF NOT EXISTS users  (
  id SERIAL PRIMARY KEY,
  email VARCHAR(50) NOT NULL,
  password TEXT NOT NULL,
  role_id INT NOT NULL REFERENCES roles(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);