CREATE TABLE IF NOT EXISTS voyages (
  id SERIAL PRIMARY KEY,
  destination VARCHAR(100) NOT NULL,
  prix NUMERIC(10,2) NOT NULL,
  places INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);